# github action for deploying main branch when pull requesting into main

name: deploy-main

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: install and build
        run: |
          npm install
          npm run build
      
      - name: test
        run: npm run test-component
      
      - name: deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
        run: curl "$DEPLOY_URL"